### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by UnexpectedLobster** [rapyuta-robotics/zethus#46]
**Describe the bug**
On start, the UI crashes and display the following error :

![image](https://user-images.githubusercontent.com/2132298/64006526-d1219680-cb12-11e9-82e7-1ee15f7bba09.png)

**To Reproduce**
1. OS: Ubuntu 18.04, Chromium 76, Node 10.16.3
2. `git clone https://github.com/rapyuta-robotics/zethus`
3. `cd zethus && npm i`
4. `npm start`
5. Open `localhost:3000` and see the error

**Comment by seadeep42** [comment]
Hi,
Thank you for reporting the issue. It's because of missing default configuration for info and tools panels.

I created a PR for fixing it. In the meantime before it's merged, pelase use this branch. (https://github.com/rapyuta-robotics/zethus/tree/bugfix/panels_config_handle_missing_info_tools)
Please let us know if you face any errors.

**Comment by UnexpectedLobster** [comment]
Hi @chaitanya-deep, thanks for your reactivity, this is working as expected.
